### ISSUE TITLE
Lower VRAM options

### ISSUE THREAD

**Issue by heavyicerx** [HelixNGC7293/DeforumStableDiffusionLocal#1]
Is it possible to add something like the "--medvram --opt-split-attention" options from the AUTOMATIC1111 webui fork for those of us without great hardware? Apologies if this is the wrong place to ask. I'm new to Git.

**Comment by HelixNGC7293** [comment]
That's a very useful feature indeed, I'll search to see how to achieve it then (or AUTOMATIC1111 can do that before me XD)

**Comment by heavyicerx** [comment]
Very cool! Thank you! I've been able to generate some huge images on my humble laptop gpu with his code.
