### ISSUE TITLE
Zoom not working.

### ISSUE THREAD

**Issue by pablopub** [HelixNGC7293/DeforumStableDiffusionLocal#19]
The zoom parameter changes nothing. I tried with 1.04 up to 10, without changes. Only translation_z works.

**Comment by ReinerBforartists** [comment]
Zoom is for 2d from what i know ...

It would be nice to have a template with explanation of all available switches and some explanation comments. But i haven't found out how to add comments to the templates yet.

**Comment by pablopub** [comment]
Oh, thank you very much!

I use https://dreamingcomputers.com/deforum-stable-diffusion/deforum-stable-diffusion-settings/ as a guide to the settings, but I missed that zoom Is 2D.
