### ISSUE TITLE
Frames per second?

### ISSUE THREAD

**Issue by walteryoung** [HelixNGC7293/DeforumStableDiffusionLocal#29]
How is Frames per Second set or determined? The examples I have run seem to be 12 fps but I don't know how that is set.

**Comment by notasecuredevice** [comment]
Its inside the run.py file on line number 1260 
`fps = 15 #@param {type:"number"}`

**Comment by HelixNGC7293** [comment]
Yup I added the "fps" parameter in txt setting file template for the latest version!
