### ISSUE TITLE
AdaBins_nyu.pt's link is down.

### ISSUE THREAD

**Issue by DuckersMcQuack** [HelixNGC7293/DeforumStableDiffusionLocal#39]
The model needs a new link.

**Comment by HelixNGC7293** [comment]
Can you try again? I just test the link it should be working now.

**Comment by DuckersMcQuack** [comment]
> Can you try again? I just test the link it should be working now.

The webpage at https://cloudflare-ipfs.com/ipfs/Qmd2mMnDLWePKmgfS8m6ntAg4nhV5VkUyAydYBp8cWWeB7/AdaBins_nyu.pt might be temporarily down or it may have moved permanently to a new web address.

Down again.
