### ISSUE TITLE
Help . ImportError: DLL load failed while importing cv2:

### ISSUE THREAD

**Issue by TimMcClane** [HelixNGC7293/DeforumStableDiffusionLocal#41]
I used deforum stable diffusion local for two weeks, but nowI have this error.

Local Path Variables:

models_path: ./models
output_path: ./output
Traceback (most recent call last):
  File "run.py", line 1312, in <module>
    main()
  File "run.py", line 79, in main
    import cv2
ImportError: DLL load failed while importing cv2: No se puede encontrar el módulo especificado.

What about this?

thank you

**Comment by screan** [comment]
hi, @TimMcClane how did you resolve? getting same error.

**Comment by TimMcClane** [comment]
Yes, I resolve this. 

solution: pip install opencv-python
