### ISSUE TITLE
Animation Prompts not working?

### ISSUE THREAD

**Issue by clover110** [HelixNGC7293/DeforumStableDiffusionLocal#44]
Hi!

Just managed to run the new updates locally, but I noticed the changes from the first animation prompt to the others are not so recognisable , in fact looks like not happening at all for me.

I copied the settings from the 'runSettings_Template.txt' file and put my own prompts in... Is there any settings I need to pay attention to?

**Comment by dbddv01** [comment]
Same here. Strange, 
"animation_prompts": {
"0": "an apple",
"12": "a banana" },
It reads the first entry 'an apple' but never reach the second entry banana. whatever the animation mode...

**Comment by dbddv01** [comment]
i think i found it.   the render.py files still contains code of v0.3 that was fixed on original deforum. Quickfix:  edit the render.py  file under the directory \helpers  and modify accordingly the wording:     **prompt_series[i]**   **with    prompt_series[int(i)]** 
under this section of python code.
# expand prompts out to per-frame\n",
        "    prompt_series = pd.Series([np.nan for a in range(anim_args.max_frames)])\n",
        "    for i, prompt in animation_prompts.items():\n",
        "   **## wrong code -->     prompt_series[i] = prompt\n"**,
        "        prompt_series[int(i)] = prompt\n",
        "    prompt_series = prompt_series.ffill().bfill()\n",
        "\n",
see https://github.com/deforum/stable-diffusion/commit/a94c324ab3154bf2930caeda3bcd14fba0b03ddc

**Comment by HelixNGC7293** [comment]
Yup I was fixed it on v0.4 but forgot to move this change back in v0.6, it should be working now.

**Comment by clover110** [comment]
Yeee! Thank you all for your speedy help and support!
Keep up the good work guys!
