### ISSUE TITLE
no module named 'ldm.models.diffusion.sampling_utiil'

### ISSUE THREAD

**Issue by TewthGnash** [HelixNGC7293/DeforumStableDiffusionLocal#51]
ive tried installing this thing multiple times now, i got all the other issues fixed via a clean install but the last two times ive tried installing ive gotten this error after trying to run: 

No module named 'ldm.models.diffusion.sampling_util'

i dont know how to fix this. ive run into so many issues with this repo it's ridiculous. this is the only stable diffusion video thing ive found that can be installed locally and i desperately want it to work. please someone help.

**Comment by TewthGnash** [comment]
@HelixNGC7293 @DGSpitzer

**Comment by ptmarks** [comment]
Getting the same error. I tried a different model, just in case that was an issue, but same error: No module named 'ldm.models.diffusion.sampling_util'. Thanks for your help.

**Comment by HelixNGC7293** [comment]
It should be fixed by now!
It's my bad, seems like the .gitignore file from original online version of deforum actually ignores the sampling_util file to be pushed to the repo (since it's in a "models/" folder which supposed to be ignored). I manually added them back, let me know if there is still any issue there👍 
Sorry for any inconvenience!

**Comment by ptmarks** [comment]
Thanks much! I will give it a go later this evening and report back.

**Comment by ptmarks** [comment]
That did the trick Everything is working now. Thanks again for your attention!

**Comment by ptmarks** [comment]
The fix worked! Thanks again.

**Comment by HelixNGC7293** [comment]
@ptmarks  That's awesome!! Let me know if you get any issues when using this project in the future.

**Comment by TewthGnash** [comment]
@HelixNGC7293 its kind of working for me now, i input the test commands for animation and i get and "EOFError ran out of input" now. help with this would be appreciated as well! thanks for fixing the last issue!

**Comment by HelixNGC7293** [comment]
> @HelixNGC7293 its kind of working for me now, i input the test commands for animation and i get and "EOFError ran out of input" now. help with this would be appreciated as well! thanks for fixing the last issue!

That's strange. Can you attach the full error message also? Did you use the sd1.5 ckpt model as well?

**Comment by TewthGnash** [comment]
im using the v1-5-pruned-emaonly.ckpt like it says in the instructions, heres the full output after i run the command:

(base) C:\Users\Bink\Desktop\DeforumStableDiffusionLocal>python run.py --enable_animation_mode --settings "./runSettings_Template.txt" --model "v1-5-pruned-emaonly.ckpt"
models_path: C:\Users\Bink\Desktop\DeforumStableDiffusionLocal\models
output_path: C:\Users\Bink\Desktop\DeforumStableDiffusionLocal\output
configs\v1-inference.yaml exists
config_path: C:\Users\Bink\Desktop\DeforumStableDiffusionLocal\configs\v1-inference.yaml
ckpt_path: C:\Users\Bink\Desktop\DeforumStableDiffusionLocal\models\v1-5-pruned-emaonly.ckpt
..loading model
No module 'xformers'. Proceeding without it.
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
Saving animation frames to C:\Users\Bink\Desktop\DeforumStableDiffusionLocal\output\2023-01\TaskName
Loading base model ()...Using cache found in C:\Users\Bink/.cache\torch\hub\rwightman_gen-efficientnet-pytorch_master
Done.
Removing last two layers (global_pool & classifier).
Building Encoder-Decoder model..Done.
Traceback (most recent call last):
  File "C:\Users\Bink\Desktop\DeforumStableDiffusionLocal\run.py", line 488, in <module>
    main()
  File "C:\Users\Bink\Desktop\DeforumStableDiffusionLocal\run.py", line 404, in main
    render_animation(args, anim_args, animation_prompts, root)
  File "C:\Users\Bink\Desktop\DeforumStableDiffusionLocal\deforum-stable-diffusion\helpers\render.py", line 235, in render_animation
    depth_model.load_adabins(root.models_path)
  File "C:\Users\Bink\Desktop\DeforumStableDiffusionLocal\deforum-stable-diffusion\helpers\depth.py", line 88, in load_adabins
    self.adabins_helper = InferenceHelper(models_path, dataset='nyu', device=self.device)
  File "C:\Users\Bink\Desktop\DeforumStableDiffusionLocal\deforum-stable-diffusion/src\infer.py", line 85, in __init__
    model, _, _ = model_io.load_checkpoint(pretrained_path, model)
  File "C:\Users\Bink\Desktop\DeforumStableDiffusionLocal\deforum-stable-diffusion/src\model_io.py", line 37, in load_checkpoint
    ckpt = torch.load(fpath, map_location='cpu')
  File "C:\Users\Bink\anaconda3\lib\site-packages\torch\serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\Bink\anaconda3\lib\site-packages\torch\serialization.py", line 920, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
EOFError: Ran out of input

**Comment by HelixNGC7293** [comment]
The model file "AdaBins_nyu.pt" may be corrupted during download? 
What is the size of the file?
It should be around 896mb




> im using the v1-5-pruned-emaonly.ckpt like it says in the instructions, heres the full output after i run the command:
> 
> (base) C:\Users\Bink\Desktop\DeforumStableDiffusionLocal>python run.py --enable_animation_mode --settings "./runSettings_Template.txt" --model "v1-5-pruned-emaonly.ckpt" models_path: C:\Users\Bink\Desktop\DeforumStableDiffusionLocal\models output_path: C:\Users\Bink\Desktop\DeforumStableDiffusionLocal\output configs\v1-inference.yaml exists config_path: C:\Users\Bink\Desktop\DeforumStableDiffusionLocal\configs\v1-inference.yaml ckpt_path: C:\Users\Bink\Desktop\DeforumStableDiffusionLocal\models\v1-5-pruned-emaonly.ckpt ..loading model No module 'xformers'. Proceeding without it. LatentDiffusion: Running in eps-prediction mode DiffusionWrapper has 859.52 M params. making attention of type 'vanilla' with 512 in_channels Working with z of shape (1, 4, 32, 32) = 4096 dimensions. making attention of type 'vanilla' with 512 in_channels Saving animation frames to C:\Users\Bink\Desktop\DeforumStableDiffusionLocal\output\2023-01\TaskName Loading base model ()...Using cache found in C:\Users\Bink/.cache\torch\hub\rwightman_gen-efficientnet-pytorch_master Done. Removing last two layers (global_pool & classifier). Building Encoder-Decoder model..Done. Traceback (most recent call last): File "C:\Users\Bink\Desktop\DeforumStableDiffusionLocal\run.py", line 488, in main() File "C:\Users\Bink\Desktop\DeforumStableDiffusionLocal\run.py", line 404, in main render_animation(args, anim_args, animation_prompts, root) File "C:\Users\Bink\Desktop\DeforumStableDiffusionLocal\deforum-stable-diffusion\helpers\render.py", line 235, in render_animation depth_model.load_adabins(root.models_path) File "C:\Users\Bink\Desktop\DeforumStableDiffusionLocal\deforum-stable-diffusion\helpers\depth.py", line 88, in load_adabins self.adabins_helper = InferenceHelper(models_path, dataset='nyu', device=self.device) File "C:\Users\Bink\Desktop\DeforumStableDiffusionLocal\deforum-stable-diffusion/src\infer.py", line 85, in **init** model, _, _ = model_io.load_checkpoint(pretrained_path, model) File "C:\Users\Bink\Desktop\DeforumStableDiffusionLocal\deforum-stable-diffusion/src\model_io.py", line 37, in load_checkpoint ckpt = torch.load(fpath, map_location='cpu') File "C:\Users\Bink\anaconda3\lib\site-packages\torch\serialization.py", line 713, in load return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args) File "C:\Users\Bink\anaconda3\lib\site-packages\torch\serialization.py", line 920, in _legacy_load magic_number = pickle_module.load(f, **pickle_load_args) EOFError: Ran out of input

**Comment by TewthGnash** [comment]
@HelixNGC7293 lol it was 0mb, i re-downloaded and it works now. thanks so much for the help!

**Comment by HelixNGC7293** [comment]
> @HelixNGC7293 lol it was 0mb, i re-downloaded and it works now. thanks so much for the help!

No problem! It's my pleasure!~
