### ISSUE TITLE
Failed to import controlnet!

### ISSUE THREAD

**Issue by nothingness6** [HelixNGC7293/DeforumStableDiffusionLocal#53]
Hi, I followed the instruction, but it showed me this error message, and I have no idea what to do. Here is the entire error message:

Failed to import controlnet! The exact error is cannot import name 'controlnet' from 'scripts' (unknown location). Deforum support for ControlNet will not be activated

Please give me the solution. 
Thanks.

**Comment by HelixNGC7293** [comment]
Hello, in which step you got this error message? What is the command you input?
In current version it shouldn't have any output message related to controlnet (The latest DeforumStableDiffusionLocal version is published long before controlnet comes out), nor the support of it..

**Comment by nothingness6** [comment]
> 

Hi, Helix. I'm grateful for your reply. I deleted everything including Python and re-installed. And then things look fine. I guess the computer should be restarted after changing the different Python version.
