### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by mickatt** [HelixNGC7293/DeforumStableDiffusionLocal#6]
Hi
Dorry for asking maybe a newbie question but i got an error when i run 
`python run.py --settings "./examples/runSettings_StillImages.txt"`

`models_path: ./models
output_path: ./output
Traceback (most recent call last):
  File "run.py", line 1312, in <module>
    main()
  File "run.py", line 112, in main
    from helpers import DepthModel, sampler_fn
ModuleNotFoundError: No module named 'helpers'`

Do you have an idea?
Thanks

**Comment by HelixNGC7293** [comment]
Did you run the setup.py code? DepthModel is from Deforum's stable diffusion repo in here: https://github.com/deforum/stable-diffusion/blob/main/helpers/depth.py
which will be cloned during running setup.py
(You can manually clone this repo if setup.py didn't work)

**Comment by mickatt** [comment]
Hi 

I ran the setup.py but it did not install this directory
I have the DeforumStableDiffusionLocal-main directory but I don't have the same files as in the Stable-Diffusion-main repository
Thanks for your answer

**Comment by mickatt** [comment]
Everything works correctly I must have done something wrong in the installation
Thanks a lot

**Comment by HelixNGC7293** [comment]
Issue Solved!
