### ISSUE TITLE
"animation_mode":"Interpolation" doesn't work when "interpolate_key_frames":true

### ISSUE THREAD

**Issue by mhnoni** [HelixNGC7293/DeforumStableDiffusionLocal#8]
Step to produce:
1- open runSettings_Template.txt
2- set animation_mode":"Interpolation"
3- make sure interpolate_key_frames":true

run python run.py --enable_animation_mode --settings "./runSettings_Template.txt"

And after rendering 3 frames, you get an error:

Global seed set to 3521683325
100%|████████████████████████████████████████████| 5/5 [00:03<00:00,  1.32it/s]
<PIL.Image.Image image mode=RGB size=512x512 at 0x16803F5E0>
Interpolation start...
Traceback (most recent call last):
  File "run.py", line 1299, in <module>
    main()
  File "run.py", line 1241, in main
    render_interpolation(args, anim_args)
  File "run.py", line 1150, in render_interpolation
    dist_frames = list(animation_prompts.items())[i+1][0] - list(animation_promp
ts.items())[i][0]
TypeError: unsupported operand type(s) for -: 'str' and 'str'

**Comment by HelixNGC7293** [comment]
This issue should be already fixed in the latest commit, you can try it out. 
Let me know if the issue still exist

**Comment by mhnoni** [comment]
> This issue should be already fixed in the latest commit, you can try it out. Let me know if the issue still exist

Hi, yes, my build was 3 days old, and looks like you fixed it, I just tested it and it worked, thanks for the quick response.
